administration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name = "administration"
urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^user_login/', views.user_login, name='user_login'),
    # url(r'^admin_home/$', views.home, name='home'),
    # url(r'^$', auth_views.login, {'template_name': 'administration/login.html'}, name='login'),
    # url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    # url(r'^change_password/$', views.change_password, name='change_password'),
    # url(r'^city/$', views.city, name='city'),
    # url(r'^city/add/$', views.add_city, name='add_city'),
    # url(r'register/$', views.register, name='user_register'),
    # url(r'^profile/$', views.view_profile, name='view_profile'),
    # url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    # url(r'^users/$', views.users, name='users'),
    # url(r'^routes/add/$', views.add_route, name='add_route'),
    # url(r'^routes/edit/(?P<id>\d+)/$', views.edit_route, name='edit_route'),
    # url(r'^routes/$', views.routes, name='routes'),
    # url(r'^stop_points/(?P<id>\d+)/$', views.stop_points, name='stop_points'),
    # url(r'^bus/add/$', views.bus_registration, name='add_bus'),
    # url(r'^bus/edit/(?P<id>\d+)/$', views.bus_edit, name='bus_edit'),
    # url(r'^bus/add_seat/(?P<id>\d+)/$', views.add_seats, name='add_seats'),
    # url(r'^bus/$', views.bus_list, name='bus_list'),
    # url(r'^schedule/add/$', views.add_schedule, name='add_schedule'),
    # url(r'^schedule/edit/(?P<id>\d+)/$', views.edit_schedule, name='schedule_edit'),
    # url(r'^schedule/detail/(?P<sid>\d+)/(?P<rid>\d+)/$', views.schedule_detail_popup, name='schedule_detail'),
    # url(r'^schedule/$', views.schedule_list, name='schedule_list'),
    # url(r'^extra_service/$', views.extra_service, name='extra_service'),
    # url(r'^extra_service/add$', views.add_extra_service, name='add_extra_service'),
    # url(r'^ferry_service/$', views.ferry_locations, name='ferry_service'),
    # url(r'^ferry_service/add$', views.add_ferry_location, name='add_ferry_service'),
    # url(r'^role/$', views.role, name='role'),
    # url(r'^role/add$', views.add_role, name='add_role'),
    # url(r'^driver/$', views.driver, name='driver'),
    # url(r'^drivers/add$', views.add_driver, name='add_driver'),
]

farm/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url
from django.template.context_processors import static
from django.views.generic import TemplateView

from dashboard import views
from farm import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^administration/',include('administration.urls')),
    url(r'^contact/', TemplateView.as_view(template_name='../templates/contact.html'),name='contact'), # /admin,/contact,/booking
]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput
from .models import City, BusInfo, Schedule, Routes, User

class register_form(UserCreationForm):
    email = forms.EmailField(required = True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(required = True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(required = True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'})
        }
        def save(self, commit=True):
            user = super(register_form, self).save(commit = False)
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data ['last_name']
            user.email = self.cleaned_data ['email']

            if commit:
                user.save()
            return user

class edit_profile_form (UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'password'
        )
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class bus_reg_form(forms.Form):
    plate_num = forms.CharField(required=True, label='Plate Number')
    type = forms.CharField(required=True, label='Bus Type')
    image = forms.FileField(required=True, label='Image (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    plate_photo = forms.FileField(required=True, label='Plate Photo (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    photo1 = forms.FileField(required=True, label='Photo 1 (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    photo2 = forms.FileField(required=True, label='Photo 2 (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    photo3 = forms.FileField(required=True, label='Photo 3 (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    photo4 = forms.FileField(required=True, label='Photo 4 (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))
    photo5 = forms.FileField(required=True, label='Photo 5 (* JPG , PNG)', widget=forms.ClearableFileInput(attrs={'multiple': False}))


    def __init__(self, *args, **kwargs):
        super(bus_reg_form, self).__init__(*args, **kwargs)
        self.fields['plate_num'].widget = TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter vehicle plate number. Example: MDY 0A-0000'})
        self.fields['type'].widget = TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter bus type'})


class bus_edit_form(forms.ModelForm):
    class Meta:
        model = BusInfo
        fields = (
            'plate_num',
            'type',
            'image',
            'plate_photo', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5',
            'is_active',
        )

    def __init__(self, *args, **kwargs):
        super(bus_edit_form, self).__init__(*args, **kwargs)
        self.fields['plate_num'].widget = TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Vehicle plate number'})

class schedule_edit_form(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = (
            'route',
            'depart_time',
            'arrive_time'
        )

    # def __init__(self, *args, **kwargs):
    #     super(schedule_edit_form, self).__init__(*args, **kwargs)
    #     self.fields['depart_date'].widget = TextInput(attrs={
    #         'class': 'form-control',
    #         'id': 'datepicker'})
    #     self.fields['depart_time'].widget = TextInput(attrs={
    #         'class': 'form-control timepicker'})

administration/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from administration.forms import register_form, edit_profile_form, bus_reg_form, \
    bus_edit_form, schedule_edit_form
from django.contrib.auth.models import User
from .models import *
import os
from django.db import connection

def index(request):
    # if not request.user.is_authenticated():
    return render(request, 'administration/login.html')
    # else:
    #     return render(request, 'dashboard/index.html', {})

def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'dashboard/index.html', {})
            else:
                return render(request, 'administration/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'administration/login.html', {'error_message': 'Invalid login'})
    return render(request, 'administration/login.html')

def home(request):
    if request.user.is_authenticated:
        return render(request, 'administration/admin_home.html')
    else:
        return redirect('login', permanent=True)

def change_password(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was updated successfully.')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'administration/user/change_password.html', {
        'form': form
    })

def register(request):
    if request.method == 'POST':
        form = register_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user_register')
    else:
        form = register_form()

        reg_form = {'form': form}
        return render(request, 'administration/user/user_register.html', reg_form)

def view_profile(request):
    if request.user.is_authenticated:
        profile = {'user': request.user}
        return render(request, 'administration/user/view_profile.html', profile)
    else:
        return redirect('login', permanent=True)

def edit_profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = edit_profile_form(request.POST, instance=request.user)

            if form.is_valid():
                form.save()
                return redirect('/administration/profile')
        else:
            form = edit_profile_form(instance=request.user)
            args = {'form': form}
            return render(request, 'administration/user/edit_profile.html', args)
    else:
        return redirect('login', permanent=True)

def users(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)
    else:
        users = User.objects.all()
        context = {
            'users': users
        }
    return render(request, 'administration/user/users.html', context)

def city(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    cities = City.objects.order_by('city_name')
    context = {
        'cities': cities
    }

    if request.method == 'POST':
        if request.POST.get('c_name'):
            post = City()
            post.city_name = request.POST.get('c_name')

            post.save()
            messages.success(request, 'New city added successfully.')
            return redirect('city')
        else:
            messages.error(request, 'Please complete all fields.')
            return redirect('city')
    else:
        return render(request, 'administration/city/city.html', context)

def add_city(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == 'POST':
        if request.POST.get('c_name'):
            post = City()
            post.city_name = request.POST.get('c_name')
            post.save()
            messages.success(request, 'New city added successfully.')
            return redirect('city')
        else:
            messages.error(request, 'Please complete all fields.')
            return redirect('city')
    else:
        return render(request, 'administration/city/add_city.html')

def routes(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    routes = Routes.objects.order_by('created_at').reverse()
    return render(request, 'administration/routes/routes.html', {'routes': routes})

def add_route(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == 'POST':
        new_route = Routes()
        new_route.depart_id = request.POST.get('depart')
        new_route.arrive_id = request.POST.get('arrive')
        new_route.approx_hr = request.POST.get('approx_hr')
        new_route.add_by = request.user
        new_route.save()
        messages.success(request, 'New route added to database')
        return redirect('routes')
    else:
        city = City.objects.order_by('city_name')
        return render(request, 'administration/routes/add_route.html', {'cities': city})

def edit_route(request, id):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == "POST":
        edit_route = Routes()
        edit_route.depart_id = request.POST.get('depart')
        edit_route.arrive_id = request.POST.get('arrive')
        edit_route.approx_hr = request.POST.get('approx_hr')
        edit_route.save()
        messages.success(request, 'Route edited')
        return redirect('routes')
    else:
        route = get_object_or_404(Routes, pk=id)
        city = City.objects.order_by('city_name')
        return render(request, 'administration/routes/edit_route.html', {'route': route, 'cities': city})

def stop_points(request, id):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == 'POST':
        new_point = StopPoints()
        new_point.route_id = id
        new_point.city_id = request.POST.get('city')
        new_point.eta = request.POST.get('approx_hr')
        new_point.save()
        return redirect('stop_points', id=id)
    else:
        route = get_object_or_404(Routes, pk=id)
        city = City.objects.order_by('city_name')
        stop_points = StopPoints.objects.filter(route_id=id)

    context = {
        'route': route,
        'cities': city,
        'stop_points': stop_points
    }
    return render(request, 'administration/routes/stop_points.html', context)

def bus_list(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == 'POST':
        bus = BusInfo()
        form = bus_reg_form(request.POST, request.FILES)
        if form.is_valid():
            bus.plate_num = form.cleaned_data['plate_num']
            bus.host_name = request.user
            bus.type = form.cleaned_data['type']
            bus.image = form.cleaned_data['image']
            if not bus.image.name.lower().endswith((".jpg", ".png")):
                messages.error(request, "* Please select only JPG or PNG image!")
            else:
                bus.save()
                return redirect('bus_list')
    else:
        form = bus_reg_form()

    bus_list = BusInfo.objects.filter(host_name=request.user)
    context = {
        'bus_list': bus_list,
        'form': form
    }
    return render(request, 'administration/bus/bus.html', context)

def bus_registration(request):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    if request.method == 'POST':
        bus = BusInfo()
        form = bus_reg_form(request.POST, request.FILES)
        if form.is_valid():
            bus.plate_num = form.cleaned_data['plate_num']
            bus.host_name = request.user
            bus.type = form.cleaned_data['type']
            bus.image = form.cleaned_data['image']
            bus.plate_photo  = form.cleaned_data['plate_photo']
            bus.photo1 = form.cleaned_data['photo1']
            bus.photo2 = form.cleaned_data['photo2']
            bus.photo3 = form.cleaned_data['photo3']
            bus.photo4 = form.cleaned_data['photo4']
            bus.photo5 = form.cleaned_data['photo5']
            if not bus.image.name.lower().endswith((".jpg", ".png")):
                messages.error(request, "* Please select only JPG or PNG image!")
            else:
                bus.save()
                return redirect('bus_list')
    else:
        form = bus_reg_form()

    context = {
        'page_title': 'Register New Vehicle',
        'form': form
    }
    return render(request, 'administration/bus/bus_edit.html', context)

def bus_edit(request, id):
    if not request.user.is_authenticated:
        return redirect('login', permanent=True)

    instance = get_object_or_404(BusInfo, pk=id)
    if not instance.host_name == request.user:
        return redirect('bus_list')

    if request.method == 'POST':
        form = bus_edit_form(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            try:
                old_file = instance.image

administration/templates/administration/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
<head>
    <meta charset="utf-8">
    <title> Farm </title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">


    <!-- #CSS Links -->
    <!-- Basic Styles -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/font-awesome.min.css' %}">

    <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-production-plugins.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-production.min.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-skins.min.css' %}">

    <!-- SmartAdmin RTL Support -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/smartadmin-rtl.min.css' %}">

    <!-- We recommend you use "your_style.css" to override SmartAdmin
         specific styles this will also ensure you retrain your customization with each SmartAdmin update.
    <link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

    <!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/demo.min.css' %}">

    <!-- #FAVICONS -->
    <link rel="shortcut icon" href="{% static 'img/core-img/logo4.jpg' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/core-img/logo4.jpg' %}" type="image/x-icon">

    <!-- #GOOGLE FONT -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- #APP SCREEN / ICONS -->
    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="{% static 'img/core-img/logo3.jpg' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/core-img/logo4.jpg' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/core-img/logo4.jpg' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/core-img/logo4.jpg' %}">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="{% static 'img/core-img/logo4.jpg' %}"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="{% static 'img/core-img/logo4.jpg' %}"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="{% static 'img/core-img/logo4.jpg' %}"
          media="screen and (max-device-width: 320px)">

</head>

<body class="animated fadeInDown">

<header id="header">

    <div id="logo-group">
{#        <span id="logo"> <img src="{% static 'img/core-img/logo4.jpg' %}" alt="Farm" style="width:25%"> </span>#}
    </div>

{#    <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs"></span> <a href="#" class="btn btn-danger">Create account</a> </span>#}
</header>

<div id="main" role="main">

    <!-- MAIN CONTENT -->
    <div id="content" class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
                <div class="hero">
                        <img src="{% static 'img/bg-img/background3.jpg' %}" class="pull-right display-image" alt="Farm"
                         style="width:100%; padding-top: 60px;">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
                <div class="well no-padding">
                    <form action="{% url 'administration:user_login' %}" id="login-form" class="smart-form client-form"
                          method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <header>
                            Sign In
                        </header>
                        <h3>Log In</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <fieldset>
                            <section>
                                <label class="label">user name</label>
                                <label class="input"> <i class="icon-append fa fa-user"></i>
                                    <input type="text" name="username">
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i>
                                        Please enter username</b></label>
                            </section>
                            <section>
                                <label class="label">Password</label>
                                <label class="input"> <i class="icon-append fa fa-lock"></i>
                                    <input type="password" name="password">
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter
                                        your password</b> </label>
                                <div class="note">
                                    <a href="forgotpassword.html">Forgot password?</a>
                                </div>
                            </section>
                        </fieldset>
                        <footer>
                            <button type="submit" class="btn btn-primary">
                                Sign in
                            </button>
                        </footer>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

<!--================================================== -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<script src="{% static 'js/plugin/pace/pace.min.js' %}"></script>

<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script> if (!window.jQuery) {
    document.write('<script src="js/libs/jquery-2.1.1.min.js"><\/script>');
} </script>

<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) {
    document.write('<script src="{% static 'js/libs/jquery-ui-1.10.3.min.js' %}"><\/script>');
} </script>

<!-- IMPORTANT: APP CONFIG -->
<script src="{% static 'js/app.config.js' %}"></script>

<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

<!-- BOOTSTRAP JS -->
<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>

<!-- JQUERY VALIDATE -->
<script src="{% static 'js/plugin/jquery-validate/jquery.validate.min.js' %}"></script>

<!-- JQUERY MASKED INPUT -->
<script src="{% static 'js/plugin/masked-input/jquery.maskedinput.min.js' %}"></script>

<!--[if IE 8]>

			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

		<![endif]-->

<!-- MAIN APP JS FILE -->
<script src="{% static 'js/app.min.js' %}"></script>

<script type="text/javascript">
    runAllForms();

    $(function () {
        // Validation
        $("#login-form").validate({
            // Rules for form validation
            rules: {
                email: {
                    required: true,
                    email: true
                },
                password: {
                    required: true,
                    minlength: 3,
                    maxlength: 20
                }
            },

            // Messages for form validation
            messages: {
                email: {
                    required: 'Please enter your email address',
                    email: 'Please enter a VALID email address'
                },
                password: {
                    required: 'Please enter your password'
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });
    });
</script>

</body>
</html>