dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = "dashboard"
urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^product/$',views.product,name='product'),
    url (r'^news/$',views.news,name='news'),
    url (r'^newdetail/$',views.newdetail,name='newdetail'),
    url (r'^shop/$',views.shop,name='shop'),
    url (r'^farmingpractice/$',views.farmingpractice,name='farmingpractice'),
    url(r'^contact/$', views.contact, name='contact'),

]

farm/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url
from django.template.context_processors import static
from django.views.generic import TemplateView

from dashboard import views
from farm import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^administration/',include('administration.urls')),
    url(r'^contact/', TemplateView.as_view(template_name='../templates/contact.html'),name='contact'), # /admin,/contact,/booking
]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
 <!-- ##### About Us Area Start ##### -->
  <section class="about-us-area">
    <div class="container">
      <div class="row align-items-center">

        <!-- About Us Content -->
        <div class="col-12 col-md-8">
          <div class="about-us-content mb-100">
            <!-- Section Heading -->
            <div class="section-heading">
              <p>About us</p>
              <h2><span>Let Us</span> Tell You Our Story</h2>
              <img src="{% static 'img/core-img/image7.jpg' %}" alt="">
            </div>
            <p>Lorem ipsum dolor sit amet, consectetu adipiscing elit. Etiam nunc elit, pretium atlanta urna veloci, fermentum malesuda mina. Donec auctor nislec neque sagittis, sit amet dapibus pellentesque donal feugiat. Nulla mollis magna non
              sanaliquet, volutpat do zutum, ultrices consectetur, ultrices at purus.</p>
            <a href="#" class="btn famie-btn mt-30">Read More</a>
          </div>
        </div>

        <!-- Famie Video Play -->
        <div class="col-12 col-md-4">
            <div class="benefits-thumbnail mb-50">
              <img src="{% static 'img/core-img/image8.png' %}" alt="">
          </div>
{#          <div class="famie-video-play mb-100">#}
{#            <img src="{% static 'img/core-img/image8.png' %}" alt="">#}
{#            <!-- Play Icon -->#}
{#            <a href="http://www.youtube.com/watch?v=7HKoqNJtMTQ" class="play-icon"><i class="fa fa-play"></i></a>#}
{#          </div>#}
        </div>

      </div>
    </div>
  </section>
  <!-- ##### About Us Area End ##### -->

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <!-- Title -->
  <title>Nobles Engine Oil Company Profile | Home</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'img/core-img/logo4.jpg'%}">
  <!-- Core Stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
  <!-- Preloader -->
  <div class="preloader d-flex align-items-center justify-content-center">
    <div class="spinner"></div>
  </div>

  <!-- ##### Header Area Start ##### -->
  <header class="header-area">
    <!-- Top Header Area -->
    <!-- Navbar Area -->
    <div class="famie-main-menu">
      <div class="classy-nav-container breakpoint-off">
        <div class="container">
          <!-- Menu -->
          <nav class="classy-navbar justify-content-between" id="famieNav">
            <!-- Nav Brand -->
            <a href="{% url 'dashboard:index' %}" class="nav-brand"><img src="{% static 'img/core-img/companylogo.jpg' %}" alt=""></a>
            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
              <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>
            <!-- Menu -->
            <div class="classy-menu">
              <!-- Close Button -->
              <div class="classycloseIcon">
                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
              </div>
              <!-- Navbar Start -->
              <div class="classynav">
                <ul>
                  <li class="active"><a href="{% url 'dashboard:index' %}">Home</a></li>
                  <li><a href="{% url 'dashboard:about' %}">About</a></li>
{#                  <li><a href="#">Pages</a>#}
{#                    <ul class="dropdown">#}
{#                      <li><a href="{% url 'dashboard:index' %}">Home</a></li>#}
{#                      <li><a href="{% url 'dashboard:about' %}">About Us</a></li>#}
{#                      <li><a href="{% url 'dashboard:farmingpractice' %}">Farming Practice</a></li>#}
{#                      <li><a href="#">Shop</a>#}
{#                        <ul class="dropdown">#}
{#                          <li><a href="{% url 'dashboard:product' %}">Our Products</a></li>#}
{#                          <li><a href="{% url 'dashboard:shop' %}">Shop</a></li>#}
{#                        </ul>#}
{#                      </li>#}
{#                      <li><a href="#">News</a>#}
{#                        <ul class="dropdown">#}
{#                          <li><a href="{% url 'dashboard:news' %}">News</a></li>#}
{#                          <li><a href="{% url 'dashboard:newdetail' %}">News Details</a></li>#}
{#                        </ul>#}
{#                      </li>#}
{#                      <li><a href="{% url 'dashboard:contact' %}">Contact</a></li>#}
{#                    </ul>#}
{#                  </li>#}
                  <li><a href="{% url 'dashboard:shop' %}"> Product</a></li>
{#                  <li><a href="{% url 'dashboard:farmingpractice' %}">Farming Practice</a></li>#}
                  <li><a href="{% url 'dashboard:news' %}">Activities</a></li>
                  <li><a href="{% url 'dashboard:contact' %}">Contact</a></li>
                </ul>
                <!-- Search Icon -->
{#                <div id="searchIcon">#}
{#                  <i class="icon_search" aria-hidden="true"></i>#}
{#                </div>#}
                <!-- Cart Icon -->

              </div>
              <!-- Navbar End -->
            </div>
          </nav>

          <!-- Search Form -->
          <div class="search-form">
            <form action="#" method="get">
              <input type="search" name="search" id="search" placeholder="Type keywords &amp; press enter...">
              <button type="submit" class="d-none"></button>
            </form>
            <!-- Close Icon -->
            <div class="closeIcon"><i class="fa fa-times" aria-hidden="true"></i></div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- ##### Header Area End ##### -->

<div id="content">
    {% block content %}
    {% endblock content %}
</div>

  <!-- ##### Footer Area Start ##### -->
  <footer class="footer-area">
    <!-- Main Footer Area -->
    <div class="main-footer bg-img bg-overlay section-padding-80-0" style="background-image: {% static 'img/bg-img/3.jpg' %}">
      <div class="container">
        <div class="row">

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <a href="#" class="foo-logo d-block mb-30"><img src="{% static 'img/core-img/logo3.jpg' %}" alt=""></a>
              <p>Lorem ipsum dolor sit amet, consecte stare adipiscing elit. In act honcus risus atiner Pellentesque risus.</p>
              <div class="contact-info">
                <p><i class="fa fa-map-pin" aria-hidden="true"></i><span>120 Raymond Rd, New York</span></p>
                <p><i class="fa fa-envelope" aria-hidden="true"></i><span>info.deercreative@gmail.com</span></p>
                <p><i class="fa fa-phone" aria-hidden="true"></i><span>+84 223 9000</span></p>
              </div>
            </div>
          </div>

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <h5 class="widget-title">QUICK LINK</h5>
              <!-- Footer Widget Nav -->
              <nav class="footer-widget-nav">
                <ul>
                  <li><a href="#">Purchase</a></li>
                  <li><a href="#">Policities</a></li>
                  <li><a href="#">Shipping</a></li>
                  <li><a href="#">FAQs</a></li>
                  <li><a href="#">Return</a></li>
                  <li><a href="#">Careers</a></li>
                  <li><a href="#">Payments</a></li>
                  <li><a href="#">Partners</a></li>
                  <li><a href="#">Guide</a></li>
                  <li><a href="#">Standard</a></li>
                  <li><a href="#">News</a></li>
                  <li><a href="#">Brands</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <h5 class="widget-title">RECENT NEWS</h5>

              <!-- Single Recent News Start -->
              <div class="single-recent-blog d-flex align-items-center">
                <div class="post-thumbnail">
                  <img src="{% static 'img/core-img/image1.jpg' %}" alt="">
                </div>
                <div class="post-content">
                  <a href="#" class="post-title">WA’s largest Car Accessories business on the market</a>
                  <div class="post-date">18 Aug 2018</div>
                </div>
              </div>

              <!-- Single Recent News Start -->
              <div class="single-recent-blog d-flex align-items-center">
                <div class="post-thumbnail">
                  <img src="{% static 'img/core-img/image2.jpg' %}" alt="">
                </div>
                <div class="post-content">
                  <a href="#" class="post-title">Engine Oil Products </a>
                  <div class="post-date">18 Aug 2018</div>
                </div>
              </div>

            </div>
          </div>

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <h5 class="widget-title">STAY CONNECTED</h5>
              <!-- Footer Social Info -->
              <div class="footer-social-info">
                <a href="#">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                  <span>Facebook</span>
                </a>
                <a href="#">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                  <span>Twitter</span>
                </a>
                <a href="#">
                  <i class="fa fa-pinterest" aria-hidden="true"></i>
                  <span>Pinterest</span>
                </a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <!-- Copywrite Area  -->
    <div class="copywrite-area">
      <div class="container">
        <div class="copywrite-text">
          <div class="row align-items-center">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
              <div class="footer-nav">
                <nav>
                  <ul>
                    <li><a href="{% url 'dashboard:about' %}">About</a></li>
                    <li><a href="#">Produce</a></li>
                    <li><a href="farming-practice.html">Practice</a></li>
                    <li><a href="#">Products</a></li>
                    <li><a href="news.html">News</a></li>
                    <li><a href="contact.html">Contact</a></li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ##### Footer Area End ##### -->

  <!-- ##### All Javascript Files ##### -->
  <!-- jquery 2.2.4  -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Owl Carousel js -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <!-- Classynav -->
  <script src="{% static 'js/classynav.js' %}"></script>
  <!-- Wow js -->
  <script src="{% static 'js/wow.min.js' %}"></script>
  <!-- Sticky js -->
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <!-- Magnific Popup js -->
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <!-- Scrollup js -->
  <script src="{% static 'js/jquery.scrollup.min.js' %}"></script>
  <!-- Jarallax js -->
  <script src="{% static 'js/jarallax.min.js' %}"></script>
  <!-- Jarallax Video js -->
  <script src="{% static 'js/jarallax-video.min.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/our-product.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
     <!-- ##### Our Products Area Start ##### -->
  <section class="our-products-area section-padding-100">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- Section Heading -->
          <div class="section-heading text-center">
            <p>Featured Products</p>
            <h2><span>Our Product</span> Are Highest Quality</h2>
            <img src="{% static 'img/core-img/decor2.png' %}" alt="">
          </div>
        </div>
      </div>

      <div class="row">

        <!-- Single Product Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-product-area mb-50">
            <!-- Product Thumbnail -->
            <div class="product-thumbnail">
              <img src="{% static 'img/bg-img/p1.jpg' %}" alt="">
              <!-- Product Tags -->
              <span class="product-tags">Hot</span>
              <!-- Product Meta Data -->
              <div class="product-meta-data">
                <a href="#" data-toggle="tooltip" data-placement="top" title="Favourite"><i class="icon_heart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Add To Cart"><i class="icon_cart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Compare"><i class="arrow_left-right_alt"></i></a>
              </div>
            </div>
            <!-- Product Description -->
            <div class="product-desc text-center pt-4">
              <a href="#" class="product-title">Strawberry</a>
              <h6 class="price">$17.99</h6>
            </div>
          </div>
        </div>

        <!-- Single Product Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-product-area mb-50">
            <!-- Product Thumbnail -->
            <div class="product-thumbnail">
              <img src="{% static 'img/bg-img/p2.jpg' %}" alt="">
              <!-- Product Meta Data -->
              <div class="product-meta-data">
                <a href="#" data-toggle="tooltip" data-placement="top" title="Favourite"><i class="icon_heart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Add To Cart"><i class="icon_cart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Compare"><i class="arrow_left-right_alt"></i></a>
              </div>
            </div>
            <!-- Product Description -->
            <div class="product-desc text-center pt-4">
              <a href="#" class="product-title">Baked Breads</a>
              <h6 class="price">$9.99</h6>
            </div>
          </div>
        </div>

        <!-- Single Product Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-product-area mb-50">
            <!-- Product Thumbnail -->
            <div class="product-thumbnail">
              <img src="{% static 'img/bg-img/p2.jpg' %}" alt="">
              <!-- Product Meta Data -->
              <div class="product-meta-data">
                <a href="#" data-toggle="tooltip" data-placement="top" title="Favourite"><i class="icon_heart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Add To Cart"><i class="icon_cart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Compare"><i class="arrow_left-right_alt"></i></a>
              </div>
            </div>
            <!-- Product Description -->
            <div class="product-desc text-center pt-4">
              <a href="#" class="product-title">Prime Beef</a>
              <h6 class="price">$59.99</h6>
            </div>
          </div>
        </div>

        <!-- Single Product Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-product-area mb-50">
            <!-- Product Thumbnail -->
            <div class="product-thumbnail">
              <img src="{% static 'img/bg-img/p4.jpg' %}" alt="">
              <!-- Product Tags -->
              <span class="product-tags bg-danger">Sale</span>
              <!-- Product Meta Data -->
              <div class="product-meta-data">
                <a href="#" data-toggle="tooltip" data-placement="top" title="Favourite"><i class="icon_heart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Add To Cart"><i class="icon_cart_alt"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Compare"><i class="arrow_left-right_alt"></i></a>
              </div>
            </div>
            <!-- Product Description -->
            <div class="product-desc text-center pt-4">
              <a href="#" class="product-title">Pure Honey</a>
              <h6 class="price"><span>$29.99</span> $19.99</h6>
            </div>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-12">
          <div class="gotoshop-btn text-center">
            <a href="{% url 'dashboard:shop' %}" class="btn famie-btn">Go to Store</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ##### Our Products Area End ##### -->
{% endblock content %}

templates/shop.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <!-- ##### Shop Area Start ##### -->
  <section class="shop-area section-padding-0-100">
  {% csrf_token %}
    <div class="container">

{#      <div class="row">#}
{#        <!-- Shop Filters -->#}
{#        <div class="col-12">#}
{#          <div class="shop-filters mb-30 d-flex align-items-center justify-content-between">#}
{#            <!-- Product Show -->#}
{#            <div class="product-show">#}
{#              <h6>Showing 1–9 of 72 results</h6>#}
{#            </div>#}
{##}
{#            <!-- Product View Mode -->#}
{#            <div class="produtc-view-mode">#}
{#              <a href="#"><i class="fa fa-th"></i></a>#}
{#              <a href="#"><i class="fa fa-list-ul"></i></a>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}

      <div class="row">
        <!-- Shop Sidebar Area -->
        <div class="col-12 col-md-4 col-lg-3">

{#          <!-- Shopping Cart -->#}
{#          <div class="shopping-cart mb-50">#}
{#            <h5 class="mb-30">Shopping Cart</h5>#}
{#            <!-- Cart Table -->#}
{#            <div class="cart-table clearfix">#}
{#              <table class="table table-responsive">#}
{#                <!-- tbody -->#}
{#                <tbody>#}
{#                  <!-- Single Table Row -->#}
{#                  <tr>#}
{#                    <td class="cart_product_img">#}
{#                      <a href="#"><img src="{% static 'img/bg-img/34.jpg' %}" alt="Product"></a>#}
{#                    </td>#}
{#                    <td class="cart_product_desc">#}
{#                      <p>Bayonne Ham</p>#}
{#                      <h6>1 x $39.99</h6>#}
{#                    </td>#}
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
{#                  </tr>#}
{#                  <!-- Single Table Row -->#}
{#                  <tr>#}
{#                    <td class="cart_product_img">#}
{#                      <a href="#"><img src="{% static 'img/bg-img/35.jpg' %}" alt="Product"></a>#}
{#                    </td>#}
{#                    <td class="cart_product_desc">#}
{#                      <p>Bayonne Ham</p>#}
{#                      <h6>1 x $39.99</h6>#}
{#                    </td>#}
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
{#                  </tr>#}
{#                  <!-- Single Table Row -->#}
{#                  <tr>#}
{#                    <td class="cart_product_img">#}
{#                      <a href="#"><img src="{% static 'img/bg-img/36.jpg' %}" alt="Product"></a>#}
{#                    </td>#}
{#                    <td class="cart_product_desc">#}
{#                      <p>Bayonne Ham</p>#}
{#                      <h6>1 x $39.99</h6>#}
{#                    </td>#}
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
{#                  </tr>#}
{#                </tbody>#}
{#              </table>#}
{#            </div>#}
{#            <!-- SubTotal -->#}
{#            <div class="cart-summary d-flex align-items-center justify-content-between">#}
{#              <div class="sub-total">#}
{#                <h6>SUBTOTAL</h6>#}
{#              </div>#}
{#              <div class="total-price">#}
{#                <h6>$52.99</h6>#}
{#              </div>#}
{#            </div>#}
{#            <!-- Checkout -->#}
{#            <a href="#" class="btn famie-btn checkout-btn mt-30 w-100">Checkout</a>#}
{#          </div>#}

   <!-- Single Widget Area -->
          <div class="single-widget-area">
            <!-- Title -->
            <h5 class="widget-title">Catagories</h5>
            <!-- Cata List -->
            <ul class="cata-list shop-page">
              <li><a href="#">All products (72)</a>
              </li>
              <li><a href="#">Freshy Fruits (20)</a></li>
              <li><a href="#">Rice &amp; Corn (15)</a></li>
              <li><a href="#">Meat &amp; Eggs (20)</a></li>
              <li><a href="#">Milk &amp; Cheese (15)</a></li>
              <li><a href="#">Others (2)</a></li>
            </ul>
          </div>

{#          <!-- Single Widget Area -->#}
{#          <div class="single-widget-area">#}
{#            <!-- Title -->#}
{#            <h5 class="widget-title">Sort by</h5>#}
{#            <!-- Cata List -->#}
{#            <ul class="cata-list shop-page">#}
{#              <li><a href="#">Top rated</a></li>#}
{#              <li><a href="#">New arrivals</a></li>#}
{#              <li><a href="#">Alphabetically, A-Z</a></li>#}
{#              <li><a href="#">Alphabetically, Z-A</a></li>#}
{#              <li><a href="#">Price: low to high</a></li>#}
{#              <li><a href="#">Price: high to low</a></li>#}
{#            </ul>#}
{#          </div>#}

{#          <!-- Single Widget Area -->#}
{#          <div class="single-widget-area">#}
{#            <!-- Title -->#}
{#            <h5 class="widget-title">Price</h5>#}
{#            <!-- Cata List -->#}
{#            <ul class="cata-list shop-page">#}
{#              <li><a href="#">$0.00 - $10.00</a></li>#}
{#              <li><a href="#">$10.00 - $50.00</a></li>#}
{#              <li><a href="#">$50.00 - $100.00</a></li>#}
{#              <li><a href="#">$100.00+</a></li>#}
{#            </ul>#}
{#          </div>#}

{#          <!-- Single Widget Area -->#}
{#          <div class="single-widget-area">#}
{#            <!-- Title -->#}
{#            <h5 class="widget-title">Tags</h5>#}
{#            <!-- Tags -->#}
{#            <ul class="famie-tags">#}
{#              <li><a href="#">All product</a></li>#}
{#              <li><a href="#">Freshy Fruit</a></li>#}
{#              <li><a href="#">Sweet Corn</a></li>#}
{#              <li><a href="#">Chicken</a></li>#}
{#              <li><a href="#">Organic</a></li>#}
{#              <li><a href="#">Meat</a></li>#}
{#            </ul>#}
{#          </div>#}

        </div>

        <!-- Shop Products Area -->
        <div class="col-12 col-md-8 col-lg-9">
          <div class="row">
           <!-- Single Product Area -->
              {% for res in datalist %}
{#            <div class="col-12 col-sm-6 col-lg-4">#}
{#              <div class="single-product-area mb-50">#}
{#                <!-- Product Thumbnail -->#}
{#                <div class="product-thumbnail">#}
{#                  <img src="{% static 'img/bg-img/p1.jpg' %}" alt="">#}
{#                  <!-- Product Tags -->#}
{#                  <span class="product-tags">Hot</span>#}
{#                  <!-- Product Meta Data -->#}
{#                  <div class="product-meta-data">#}
{#                    <a href="#" data-toggle="tooltip" data-placement="top" title="Favourite"><i class="icon_heart_alt"></i></a>#}
{#                    <a href="#" data-toggle="tooltip" data-placement="top" title="Add To Cart"><i class="icon_cart_alt"></i></a>#}
{#                    <a href="#" data-toggle="tooltip" data-placement="top" title="Compare"><i class="arrow_left-right_alt"></i></a>#}
{#                  </div>#}
{#                </div>#}
{#                <!-- Product Description -->#}
{#                <div class="product-desc text-center pt-4">#}
{#                  <a href="#" class="product-title">Strawberry</a>#}
{#                  <h6 class="price">$17.99</h6>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
                  <div class="col-12 col-sm-6 col-lg-4">

          <!-- Shopping Cart -->
{#          <div class="shopping-cart mb-50">#}
{#            <h5 class="mb-30">Shopping Cart</h5>#}
            <!-- Cart Table -->
            <div class="cart-table clearfix">
              <table class="table table-responsive">
                <!-- tbody -->
                <tbody>
                  <!-- Single Table Row -->
                  <tr>
                    <td class="cart_product_img">
                      <a href="#"><img src="{% static 'img/core-img/image5.jpg' %}" alt="Product"></a>
                    </td>
                    <td class="cart_product_desc">
                      <p>Bayonne Ham</p>
{#                      <h6>1 x $39.99</h6>#}
                        <a href="{% url 'dashboard:newdetail' %}">Detail</a>
                    </td>
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
                  </tr>
{#                  <!-- Single Table Row -->#}
{#                  <tr>#}
{#                    <td class="cart_product_img">#}
{#                      <a href="#"><img src="{% static 'img/bg-img/35.jpg' %}" alt="Product"></a>#}
{#                    </td>#}
{#                    <td class="cart_product_desc">#}
{#                      <p>Bayonne Ham</p>#}
{#                      <h6>1 x $39.99</h6>#}
{#                    </td>#}
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
{#                  </tr>#}
{#                  <!-- Single Table Row -->#}
{#                  <tr>#}
{#                    <td class="cart_product_img">#}
{#                      <a href="#"><img src="{% static 'img/bg-img/36.jpg' %}" alt="Product"></a>#}
{#                    </td>#}
{#                    <td class="cart_product_desc">#}
{#                      <p>Bayonne Ham</p>#}
{#                      <h6>1 x $39.99</h6>#}
{#                    </td>#}
{#                    <td class="pro-close">#}
{#                      <a href="#"><i class="icon_close"></i></a>#}
{#                    </td>#}
{#                  </tr>#}
                </tbody>
              </table>
            </div>
{#          </div>   #}

        </div>
              {% endfor %}



          </div>

          <!-- Pagination -->
          <nav>
            <ul class="pagination mb-0 mt-50">
              <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </nav>
        </div>
      </div>

    </div>
  </section>
  <!-- ##### Shop Area End ##### -->
{% endblock content %}